<?php
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/11/2 10:43
 * @User: kevin
 * @Current File : AttachmentCategory.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\admin\controller;


use think\App;
use app\common\models\AttachmentCategory as CategoryModel;
use app\admin\validate\AttachmentCategory as CategoryValidate;

/**
 * Class AttachmentCategory
 * @package app\admin\controller
 */
class AttachmentCategory extends Base
{
    public function __construct(App $app = null)
    {
        parent::__construct($app);
    }

    /**
     * @return Base|void
     */
    public function initialize()
    {
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return false|mixed|string
     */

    public function add(){
        if($this->request->isGet()){
            $data=(new CategoryModel())->getCategoryTree();
            $this->assign('category',$data);
            return $this->fetch();
        }
        if($this->request->isPost()){
            //todo:: 保存方法
            $data=input('post.','','htmlspecialchars,trim');
            $validate=new CategoryValidate();
            if(!$validate->scene('add')->check($data)){
                return show(false, $validate->getError(), '');
            }
            try{
                if(!(new CategoryModel())->save($data)) return show(false,'新增失败','');
                 return show(true,'新增成功','http://www.baidu.com');
            }catch (\Exception $exception){
                return show(false,$exception->getMessage(),'');
            }

            return ;
        }
        return show(0,'非法访问');//功能完善后再来修饰

    }
}