<?php
/**
 * @Create by PhpStorm
 * @author:jinxiu89@163.com
 * @Create Date:2020/8/12 16:05
 * @User: kevin
 * @Current File : Driver.php
 * @格言：溪涧岂能留得住，终归大海做波涛 --李忱
 * @格言： 我的内心因看见大海而波涛汹涌
 **/

namespace app\admin\controller;


use think\facade\Config;
use app\admin\controller\Base;
/**
 * Class Driver
 * @package app\admin\controller
 */
class Driver extends Base
{
    /**
     * @return Base|void
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * @return mixed
     */
    public function index()
    {
        $prefix=Config::get('app.aws_key_prefix.dw').input('get.prefix','','trim');
        $list = \app\common\helper\Aws::lists($prefix);
        print_r($list);
        return $this->fetch();
    }
}